# Generated by Django 5.1.1 on 2024-10-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_remove_student_enrollment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
