# Generated by Django 5.1.1 on 2024-10-06 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('title', models.CharField(max_length=60)),
                ('subject_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('subject_term', models.CharField(choices=[('1', 'First Term'), ('2', 'Second Term')], default='1', max_length=6)),
                ('subject_year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2024)),
                ('avilable_seat', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('subject_is_open', models.BooleanField()),
            ],
        ),
    ]
