# Generated by Django 5.1.1 on 2024-10-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegCN', '0002_quotarequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
